name: ci

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ACCOUNT_ID: "753172984754"
      AWS_ROLE_ARN: arn:aws:iam::753172984754:role/GitHubActionsOIDCRoleFor_datahaikuninja_ecspresso-demo-app
      AWS_REGION: ap-northeast-1

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "${{ env.AWS_ACCOUNT_ID}}"
          echo "${{ env.AWS_ROLE_ARN}}"
          echo "${{ env.AWS_REGION}}"

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - run: echo "${GITHUB_REF##*/}"
