name: ci

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.release.tag_name }}"
          echo "${GITHUB_REF}"
          echo "${GITHUB_REF##*/}"
